# ===================================
#  Form Behavior Config
# ===================================

name: User
form: @/plugins/rainlab/user/models/user/fields.yaml
model-class: RainLab\User\Models\User
default-redirect: rainlab/user/users

create:
    redirect: rainlab/user/users/update/:id
    redirect-close: rainlab/user/users

update:
    redirect: rainlab/user/users
    redirect-close: rainlab/user/users
