# ===================================
#  List Behavior Config
# ===================================

title: Manage Users
list: @/plugins/rainlab/user/models/user/list_columns.yaml
model-class: RainLab\User\Models\User
record-url: rainlab/user/users/update/:id
no-records-message: backend::lang.list.no_records
records-per-page: 5
show-checkboxes: yes

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt



